export default {
    contacts: [
        {
            id: 1,
            name: 'Veronica Salmon',
            image: require('../../assets/images/image_22.png'),
            appUser: false,
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean purus lorem, finibus sed vestibulum id, ultricies a risus. Ut mauris lorem, viverra vel luctus vel, efficitur eget turpis. Integer non rutrum urna. Suspendisse mauris dolor, maximus vel posuere eu, euismod nec velit. Mauris sit amet malesuada ipsum, sed eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-missed',
                length: '31',
            },
        },
        {
            id: 2,
            name: 'Christina Michael',
            image: null,
            appUser: false,
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-missed',
                length: '31',
            },
        },
        {
            id: 3,
            name: 'Sam Taylor',
            image: null,
            appUser: false,
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
        {
            id: 4,
            name: 'Michael Smith',
            image: require('../../assets/images/image_22.png'),
            appUser: false,
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-outgoing',
                length: '31',
            },
        },
        {
            id: 5,
            name: 'Chuck Norris',
            image: null,
            message: 'Interdum et malesuada.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
        {
            id: 6,
            name: 'Christina Salmon',
            image: require('../../assets/images/image_22.png'),
            appUser: true,
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
        {
            id: 7,
            name: 'Chris Brown',
            appUser: false,
            image: require('../../assets/images/image_22.png'),
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
        {
            id: 8,
            name: 'Salvador Dali',
            image: null,
            appUser: false,
            message:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a dictum arcu, a rhoncus tortor. Sed ut tristique risus. Interdum et malesuada fames eleifend eros. Nulla vitae est faucibus velit vehicula ornare.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
        {
            id: 9,
            name: 'Ali Veli',
            image: require('../../assets/images/image_22.png'),
            appUser: true,
            message: 'Interdum et malesuada.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
        {
            id: 10,
            name: 'Alice Malice',
            image: require('../../assets/images/image_22.png'),
            appUser: true,
            message: 'Sed ut tristique ris.',
            callSummary: {
                type: 'phone-incoming',
                length: '31',
            },
        },
    ],

    user: {
        name: 'Michael Smith',
        email: 'michael.smith@example.com',
        credits: 32.0,
        international_credits: 12.0,
    },

    phoneContacts: [
        {
            contactType: 'person',
            firstName: '4b',
            id: '9480',
            imageAvailable: false,
            lastName: 'Landlords',
            lookupKey: '1885r9304-1A2B2F4543293F2F3F29432F3F454B2F4D',
            middleName: 'Donald',
            name: '4b Donald Landlords',
            phoneNumbers: [
                {
                    id: '37258',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07741 647515',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Aislinn',
            id: '15164',
            imageAvailable: false,
            lookupKey: '1885r14612-2A3A4E403A4444.3789r14613-2A3A4E403A4444',
            name: 'Aislinn',
            phoneNumbers: [
                {
                    id: '58350',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+49 1512 0268419',
                    type: '2',
                },
                {
                    id: '58356',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+4915120268419',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Archie',
            id: '5912',
            imageAvailable: false,
            lastName: 'BOXEVER',
            lookupKey: '1885r5826-294B2D3739312B45573153314B',
            name: 'Archie BOXEVER',
            phoneNumbers: [
                {
                    id: '23243',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '02079937136',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Aydin',
            id: '129',
            imageAvailable: false,
            lookupKey: '1885r96-2A5A303A44.3789r123-2A5A303A44.1419r18594-2A5A303A44',
            name: 'Aydin',
            phoneNumbers: [
                {
                    id: '352',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '078-774-34637',
                    type: '2',
                },
                {
                    id: '487',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07877434637',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Ben',
            id: '9688',
            imageAvailable: false,
            lookupKey: '1885r9306-2B3143.3789r9512-2B3143',
            name: 'Ben',
            phoneNumbers: [
                {
                    id: '37262',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07817757563',
                    type: '2',
                },
                {
                    id: '38087',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07817757563',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Blue',
            id: '19028',
            imageAvailable: true,
            lastName: 'Folding',
            lookupKey: '2099r15222-2C405232344640303A4436',
            name: 'Blue Folding',
            phoneNumbers: [
                {
                    id: '60773',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+447969795520',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Boggy',
            id: '120',
            imageAvailable: false,
            lookupKey: '1885r92-2C4636365A.3789r114-2C4636365A.1419r18617-2C4636365A',
            name: 'Boggy',
            phoneNumbers: [
                {
                    id: '339',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '077-301-96281',
                    type: '2',
                },
                {
                    id: '340',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '077-301-96281',
                    type: '2',
                },
                {
                    id: '442',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07730196281',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Brian',
            id: '13303',
            imageAvailable: false,
            lastName: 'Dwcc',
            lookupKey: '3789r12795-2B4B3929432F552D2D',
            name: 'Brian Dwcc',
            phoneNumbers: [
                {
                    id: '51198',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+447415764249',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Brian',
            id: '19032',
            imageAvailable: true,
            lastName: 'Dwcc',
            lookupKey: '2099r15226-2C4C3A2A4430562E2E',
            name: 'Brian Dwcc',
            phoneNumbers: [
                {
                    id: '60785',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+447415764249',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Brogan',
            id: '117',
            imageAvailable: false,
            lookupKey: '1885r59-2B4B45352943.3789r128-2B4B45352943',
            name: 'Brogan',
            phoneNumbers: [
                {
                    id: '261',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '077-883-39119',
                    type: '2',
                },
                {
                    id: '262',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '077-883-39119',
                    type: '2',
                },
                {
                    id: '512',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07788339119',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Bt',
            id: '77',
            imageAvailable: false,
            lookupKey: '1885r74-2B4F',
            name: 'Bt',
            phoneNumbers: [
                {
                    id: '300',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '080-080-0150',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Callum',
            id: '13307',
            imageAvailable: false,
            lastName: 'Dwcc',
            lookupKey: '3789r12799-2D293F3F51412F552D2D',
            name: 'Callum Dwcc',
            phoneNumbers: [
                {
                    id: '51218',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07860673279',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Callum',
            id: '19034',
            imageAvailable: true,
            lastName: 'Dwcc',
            lookupKey: '2099r15228-2E2A4040524230562E2E',
            name: 'Callum Dwcc',
            phoneNumbers: [
                {
                    id: '60791',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07860673279',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Caspar Student',
            id: '104',
            imageAvailable: false,
            lastName: 'Rd',
            lookupKey: '1885r85-2D294D47294B4D4F512F31434F353F452D4D4F314B4B2F.3789r101-2D294D47294B4D4F512F31434F353F452D4D4F314B4B2F',
            middleName: 'Glocster',
            name: 'Caspar Student Glocster Rd',
            phoneNumbers: [
                {
                    id: '322',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '079-494-35592',
                    type: '2',
                },
                {
                    id: '323',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '079-494-35592',
                    type: '2',
                },
                {
                    id: '377',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07949435592',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Cemil',
            id: '38',
            imageAvailable: false,
            lookupKey: '1885r37-2D3141393F',
            name: 'Cemil',
            phoneNumbers: [
                {
                    id: '203',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '073-805-33359',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Charlotte',
            id: '13301',
            imageAvailable: false,
            lastName: 'Meyer',
            lookupKey: '3789r12793-2D37294B3F454F4F31413159314B',
            name: 'Charlotte Meyer',
            phoneNumbers: [
                {
                    id: '51188',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07703418870',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Charlotte',
            id: '19037',
            imageAvailable: true,
            lastName: 'Meyer',
            lookupKey: '2099r15231-2E382A4C404650503242325A324C',
            name: 'Charlotte Meyer',
            phoneNumbers: [
                {
                    id: '60800',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07703418870',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Cheltenham Garage',
            id: '81',
            imageAvailable: false,
            lookupKey: '1885r78-2D37313F4F314337294135294B293531',
            name: 'Cheltenham Garage',
            phoneNumbers: [
                {
                    id: '308',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '011-796-74134',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Chris',
            id: '11259',
            imageAvailable: false,
            lastName: 'Ep',
            lookupKey: '1885r10977-2D374B394D3147.3789r10978-2D374B394D3147',
            name: 'Chris Ep',
            phoneNumbers: [
                {
                    id: '43982',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07446 972666',
                    type: '2',
                },
                {
                    id: '43988',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '07446972666',
                    type: '2',
                },
            ],
        },
        {
            contactType: 'person',
            firstName: 'Chris',
            id: '111',
            imageAvailable: false,
            lastName: 'KM',
            lookupKey: '1885r89-2D374B394D3D41.3789r108-2D374B394D3D41',
            name: 'Chris KM',
            phoneNumbers: [
                {
                    id: '333',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+447758358551',
                    type: '2',
                },
                {
                    id: '412',
                    isPrimary: 0,
                    label: 'mobile',
                    number: '+447758358551',
                    type: '2',
                },
            ],
        },
    ],
};
